### ISSUE TITLE
YouTube tutorial

### ISSUE THREAD

**Issue by infamouskoala** [infamouskoala/koalahook#1]
will be released soon, don't mention it to me i already am aware of it. I will also update the hyperlink once i upload it

**Comment by YexoCxdes** [comment]
wheres the ututorial https://yexo.hacked-your.webcam/LiveStream//5gurkas4.png

**Comment by infamouskoala** [comment]
https://www.youtube.com/watch?v=6NJjPMd2siw&t=10s
