### ISSUE TITLE
brah wtf brah

### ISSUE THREAD

**Issue by 0x-Stealth** [infamouskoala/koalahook#3]
LKMFAOOO NVM IM ACOUSTIC UR RICE JUST LOOKS LIKE WINDOWS

**Comment by 0x-Stealth** [comment]
Wait what the fuck this is windows

How did you fucking rice windows wtf :sob:

**Comment by 0x-Stealth** [comment]
Holy shit i'm too tired for this shit what the fuck that isn't even nvim that's irc that for some reason looks like kickstar.nvim 

Wtf brah

**Comment by infamouskoala** [comment]
Can you speak english please?
